from turtle import *
abc= Turtle()
screen = Screen()
screen.bgcolor("yellow")
abc.color('Red')
abc.pensize(2)
abc.speed(4)
abc.forward(80)
abc.left(44)
abc.forward(230)
abc.right(10)
abc.forward(10)
abc.circle(22)
abc.backward(40)
abc.forward(230)
abc.right(10)
abc.circle(54)
abc.forward(230)
abc.right(10)
mainloop()