from turtle import *
abc= Turtle()
abc.color('Red')
abc.pensize(2)
abc.speed(0.5)
abc.forward(80)
abc.left(50)
abc.forward(200)
abc.right(150)
abc.forward(50)
abc.circle(25)
abc.backward(30)
abc.circle(50)
mainloop()